- name: jenkinse sleve
  remote_user: ubuntu
  hosts: host
  tasks:
    - name: update
      become: true
      command: apt-get update -y

    - name: insatall jdk
      become: true
      command: apt-get install openjdk-8-jdk -y

    - name: insatall docker
      become: true
      command: apt install docker.io -y

    - name: move to  /home/ubuntu
      command: chdir=/home/ubuntu curl -o agent.jar http://34.133.211.58/jnlpJars/agent.jar
    - name: copy env file to slave
      copy:
        src: ./.env
        dest: /home/ubuntu
